source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "minimal-mistakes-jekyll", "~> 4.20.0"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "rake", "~> 13.0.3"
gem "jekyll-scholar", "~> 7.1.3"
gem "bibtex-ruby"
gem "rouge"
gem 'sassc', '~> 2.1.0'
group :jekyll_plugins do
end
gem 'webrick', '~> 1.7.0'

