source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "minimal-mistakes-jekyll", :github => "mmistakes/minimal-mistakes"
group :jekyll_plugins do
end
